# Generated by Django 4.0 on 2021-12-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmonials',
            name='image_name',
        ),
        migrations.AddField(
            model_name='testmonials',
            name='testmony',
            field=models.TextField(null=True),
        ),
    ]
