# Generated by Django 3.2.9 on 2021-12-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testmonials_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='message',
            field=models.TextField(),
        ),
    ]
